### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by evanarkko** [salsam/simpleChessAI#1]
Moikka!
Pullasin reposi tiistaina 16.8. 10:00
Aihevalintasi on hyvä ja minulle mielenkiintoinen, joten oli kiva katselmoida koodiasi. Aivan kaikkea en tajunnut, mutta aika kokonaisvaltaisesti kuitenkin.

Vanha projektisi olikin jo laaja (Javalabra?) ja mielestäni hyvin toteutettu. Nimesit pakkauksesi ja luokkasi kauniisti. Tämä helpotti lukua. Toisaalta itse koodissa useat metodit ja jotkin muuttujien nimet olivat pitkähköjä ja kerrytti turhaa tekstimassaa koodin sekaan. Tämä on osaksi toki myös tyylikysymys. Tarvittavat selittelyt voisi olla JavaDocissa ja kommenteissa. Nämä osapuolet olivat sinulla erittäin selvät ja kattavat ne auttoivat kovasti ymmärtämään mitä monimutkaisissa metodeissa oikein tehdään. 

Metodisi pysyivät tarpeeksi lyhyinä. Välillä arvojen saamiseksi kutsut arvoja palauttavia metodeja useaan kertaan. Sorrun tähän jatkuvasti itsekin. Tämä myös tekee koodista pitkää ja vaikealukuista. Käytit rivinvaihtoa ihan näppärästi mutta kannattaa ehkä myös useammin harkita lokaalien muuttujien luomista funktion alussa lyhenntääksesi tekstiä. Luokkasi oli kuitenkin vajaat 250-riviä ja siinä saadaan jo aika paljon aikaan eli hyvä :). 

Koodisi vaikuttaa olevan tehokas ja turhia asioita ei ole ilmiselvästi paljon. Käytät (ja olet toteuttanut) taitavasti tietorakenteita kuten HashSet ja TranspositionKey (aivan uusi mulle). Ainoa silmäänpistävä asia tehokkuuden kannalta oli, että parhaiden samanarvoisten siirtojen arpova metodi getBestMove() luo jokaisella kutsukerralla uuden Random-olion. Voisikohan se olla jopa private final- tyyppinen muuttuja koko luokalle? 

Sitten itse peliin. Pelaaja vs. AI moodissa pelaaja pelaa ensinnäkin väärinpäin ruudulta katsoen :D.
Ehkä olet muuttamassa tämän muutenkin vielä. AI:n siirrot etenevät todella hitaasti ja AI vs. AI peli näyttää loppuvan 3 siirron jälkeen. Nämä kolme siirtoa ovat lähes joka kerta täysin samat, poiketen vain yhdellä siirrolla joskus. Lisäksi AI siirsi samanlaisen aloitussiirron pelaajaa vastaan. Ehkä huvin vuoksi variaatiota voisi vieläkin lisätä (ehkä vain aloitukseen, ettei koko äly mene huonoksi?). Siirtojen välinen aika on tosiaan hyvin pitkä. En löytänyt ns. Pelimoottorieita, missä näkyy Thread.sleep(long mls) tai Timer-oliota, joten en saanut selville kuinka usein rekursoit/maalaat uudestaan milloinkin.

Huomasin, että otat huomioon siirron sijaintiin vaikuttavat tekijät arvioidessasi siirron kannattavuutta. Siistiä! Oikeaa shakkia! Projektisi ja koodisi oli kokonaisuudeltaan ihailtavan näköistä ja uskon oppineeni siitä yhtä jos toista. Kiitos!

**Comment by salsam** [comment]
Paljon kiitoksia palutteesta!

Metodien nimet ovat kieltämättä varsin pitkiä, sillä en ole hyvä keksimään lyhyitä, kuvailevia nimiä :(, mutta katson vielä josko onnistuisi. Tuo arvojen tallentamineen apumuttujiin tosiaan oli itselläni aiemin tapana, mutta toisaalta kuulin turhan tallentelun taas hidastavan ohjelmaa. Päädyin kutsumaan samaa metodia uudelleen vain vakionopeuksisilla kutsuilla, mutta itsekin olen pohtinut tuota, enkä ole aivan varma kumpi tapa on parempi (selkeys vs pieni tehokkuusero ja turha koodi).

TranspositionKey on muuten vain oma tietorakenteeni, jota käytän transpositiotaulun avaimena, jotta samanlaisessa tilanteessa ei tilannetta tarvitse evaluoida uudelleen.

Mitä AI:n toimintaan tulee voisin ehkä kääntää laudan. Satunnaisuus oli minullakin mielessä ja jos jaksaisin, voisin esim. tallentaa siirrot, jotka ovat arvoltaan tietyn rajan (esim 10 cp?) päässä parhaasta löydetystä ja arpoa sitten näistä. Tämä laskisi periaatteessa tekoälyn tasoa hieman, mutta satunnaisuus tosiaan tekisi tekoälystä kivemman katsoa.

Ohjelmassani ei ole game-looppia, koska en periaatteessa tarvitse sitä, vaan ohjelmani perustuu kahteen "tilaan". Joko nappula on valittuna, tai ei ole. Näin ruutu päivittyy vain ruutua klikatessa vähentäen turhaa kuormitusta. Sivuvaikutuksena tekoäly tekee siirron vain pelaajan klikattua ruutua, sillä muulloin tekoälyn siirtoja voisi olla todella ikävä katsoa tekoälyn siirtäessä nappulaa esim. kerran 0.1 sekunnissa. Tehokkuusongelmaan en oikeastaan osaa sanoa mitään, sillä omalla surkealla läppärilläni siirrot tapahtuivat alle 5s rekursiosyvyydellä 3 ja yliopiston koneilla tähän meni alle 1s. Kyselin tästä tänään ohjauksessa ja ehkä syynä on muistivaatimus, sillä tallennan kaikkien pelitilanteiden arvot muistiin, jolloin muistivaatimuskin on eksponentiaalinen. Tähän voisi ehkä laittaa rajoituksen tallentaen vain esim. 50000 viime tilannetta tms.
