### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by lecromine** [salsam/simpleChessAI#2]
Koodia on helppoa ymmärtää, sillä se on selkeästi kirjoitettua. Javadoc on paikoin turhan monisanaista – tosin varmaankin lukija, joka ei ole kovin kokenut koodaamaan tai tunne tietorakenteisiin liittyviä peruskäsitteitä, on kiitollinen perusteellisuudesta. Toiminnallisuuden ymmärtämiseen ei mene turhaan aikaa, koska metodeilla ja muuttujilla on päävaltaisesti itsensä selittävät nimet. Luokkien vastuujaottelu on myös hyvin mietitty, sillä luokat eivät ole liian pitkiä eivätkä sekavia. Sama juttu pakettien kanssa.

Tehtävä on ollut varmasti työläs, mutta jälki on erittäin huolellista. Jopa ihailtavaa. Toiminnallisuuksista on hankala yrittää keksiä mitään korjattavaa/kehitettävää, koska mielestäni kaikki näyttää puhtaalta ja hyvin toimivalta. Paremmalta kuin mitä itse pystyisin kehittelemään.

En ole varma, onko vika netbeansissa, koneessa vai minussa, mutta jostain syystä pelissä AI:ta vastaan pelaaja joutuu klikkaamaan ruutua jokaisen siirron jälkeen, että AI reagoisi. Huomasin myös pelatessani, että välillä peli bugaa ja siirtelee nappuloitani. En onnistunut paikallistamaan bugin lähdettä, koska uudelleen pelatessani samaa ongelmaa ei enää ollut. Pelasin vaikeustasolla 1000 ja värinä musta, kun bugi ilmeni.

Ainakin oletusvaikeustasolla AI hölmöilee suhteellisen paljon. Shakata se kuitenkin osaa ja löytää välillä strategisia aukkoja, jos ei keskity peliin, mikä on osoitus siitä, että AI:n peruslogiikka on oikean suuntaista. 

Kaiken kaikkiaan jälkesi on erittäin vaikuttava ja osoittaa, että olet joko käyttänyt ohjelmaan todella paljon aikaa, olet todella kokenut koodaaja ja erityisesti pelien kanssa – tai sitten kumpaakin.

**Comment by salsam** [comment]
Kiitoksia palautteesta!

Pelaaja muuten joutuu klikkaamaan tekoälyn vuorolla siksi, että jos laittaisin tekoälyn siirtämään automaattisesti, olisi tekoälyjen peliä mahdoton seurata nopeuden takia. Toisaalta shakkihan on vuoroihin perustuva strategiapeli, joten ajattelin ettei tämä ole kovin paha. Näin en edes tarvitse gameloppia, koska pelissäni on vain 2 tilaa - nappula valittu tai nappulaa ei valittu.

Pelini on äskettäin törmännyt muutamaan bugiin, jotka valitettavasti ilmenevät tekoälyn hölmöilynä. Sain tänään tuon pahimman hölmöilyn korjattua ottamalla dynaamista muistia käyttävän tauluni toistaiseksi pois, sillä siinä ilmeisesti tuli liikaa hash collisioneita. Hyvä, että mainitsit tuon, sillä en itse ollut tajunnut sitä vaan ajattelin tekoälyn vain käyttävän todella vähän aikaa (itse testailen lähinnä 1/10 oletusvaikeustasolla voidakseni nähdä pelin kehittyminen maksiminopeudella).

 Nappuloiden siirtely johtuu nk. Play again- bugist mitä luultavimmin, sillä koodasin sen aiheuttaman virheen toistaiseksi pois vain kiertämällä NullPointerExceptionit, jolloin osa kokeilluista siirroista jää kumoamatta, mutta peli ei kaadu. Tämä bugi on kiusannut minua jo ainakin viikon ja ilmenee lähinnä vain pelaajan halutessa pelata uudestaan. En juuri ole testannut uudelleen pelaamista, joten bugi voi olla todella vanha ja saattaa olla etten löydä sitä.
